const creatures = [
        {   id:0,
            name: "Aarakocra",
            cr:0.25,
            type: "humanoid",
            size: "medium",
            ac: 12,
            hp: 13,
            initiative: 2,
            alignment: "neutral",
            speed:{
                fly: true,
                swim: false,
                walk: true,
                climb: false,
            },
            legendary: false,
            Environment: {
                Desert: false,
                Mountain: true,
                Grassland: false,
                Forest: false,
                Hill: true,
                Swamp: false,
                Urban: false,
                Artic: false,
                Underdark: false,
                Underwater: false,
                Coastal: true
            }
        },
        {   id:2,
            name: "Aboleth",
            cr:10,
            type: "aberration",
            size: "large",
            ac: 17,
            hp: 135,
            initiative: -1,
            alignment: "lawful evil",
            speed:{
                fly: false,
                swim: true,
                walk: true,
                climb: false,
            },
            legendary: true,
            Environment: {
                Desert: false,
                Mountain: false,
                Grassland: false,
                Forest: false,
                Hill: false,
                Swamp: false,
                Urban: false,
                Artic: false,
                Underdark: true,
                Underwater: true,
                Coastal: false
            }
        },
        {   id:3,
            name: "Abominable Yeti",
            cr:9,
            type: "monstrosity",
            size: "huge",
            ac: 15,
            hp: 137,
            initiative: 0,
            alignment: "chaotic evil",
            speed:{
                fly: false,
                swim: false,
                walk: true,
                climb: true,
            },
            legendary: false,
            Environment: {
                Desert: false,
                Mountain: true,
                Grassland: false,
                Forest: false,
                Hill: false,
                Swamp: false,
                Urban: false,
                Artic: true,
                Underdark: false,
                Underwater: false,
                Coastal: false
            }
        },
        {   id:4,
            name: "Acolyte",
            cr:0.25,
            type: "humanoid",
            size: "medium",
            ac: 10,
            hp: 9,
            initiative: 0,
            alignment: "any",
            speed:{
                fly: false,
                swim: false,
                walk: true,
            },
            legendary: false,
            Environment: {
                Desert: true,
                Mountain: true,
                Grassland: true,
                Forest: true,
                Hill: true,
                Swamp: true,
                Urban: true,
                Artic: true,
                Underdark: true,
                Underwater: true,
                Coastal: true
            }
        },
        {   id:5,
            name: "Adult Black Dragon",
            cr:14,
            type: "dragon",
            size: "huge",
            ac: 19,
            hp: 195,
            initiative: 2,
            alignment: "chaotic evil",
            speed:{
                fly: true,
                swim: true,
                walk: true,
                climb: false,
            },
            legendary: true,
            Environment: {
                Desert: false,
                Mountain: false,
                Grassland: false,
                Forest: false,
                Hill: false,
                Swamp: true,
                Urban: false,
                Artic: false,
                Underdark: false,
                Underwater: false,
                Coastal: true
            }
        },
        {   id:6,
            name: "Adult Blue Dracolich",
            cr:17,
            type: "undead",
            size: "huge",
            ac: 19,
            hp: 225,
            initiative: 0,
            alignment: "lawful evil",
            speed:{
                fly: true,
                swim: false,
                walk: true,
                climb: false,
            },
            legendary: true,
            Environment: {
                Desert: true,
                Mountain: true,
                Grassland: false,
                Forest: false,
                Hill: false,
                Swamp: false,
                Urban: false,
                Artic: false,
                Underdark: false,
                Underwater: false,
                Coastal: false
            }
        },
        {   id:7,
            name: "Adult Blue Dragon",
            cr:16,
            type: "dragon",
            size: "huge",
            ac: 19,
            hp: 225,
            initiative: 0,
            alignment: "lawful evil",
            speed:{
                fly: true,
                swim: false,
                walk: true,
                climb: false,
            },
            legendary: true,
            Environment: {
                Desert: true,
                Mountain: true,
                Grassland: false,
                Forest: false,
                Hill: false,
                Swamp: false,
                Urban: false,
                Artic: false,
                Underdark: false,
                Underwater: false,
                Coastal: false
            }
        },
        {   id:8,
            name: "Adult Brass Dragon",
            cr:13,
            type: "dragon",
            size: "huge",
            ac: 18,
            hp: 172,
            initiative: 0,
            alignment: "chaotic good",
            speed:{
                fly: true,
                swim: false,
                walk: true,
                climb: false,
            },
            legendary: true,
            Environment: {
                Desert: true,
                Mountain: true,
                Grassland: false,
                Forest: false,
                Hill: false,
                Swamp: false,
                Urban: false,
                Artic: false,
                Underdark: false,
                Underwater: false,
                Coastal: false
            }
        },
        {   id:8,
            name: "Adult Bronze Dragon",
            cr:15,
            type: "dragon",
            size: "huge",
            ac: 19,
            hp: 212,
            initiative: 0,
            alignment: "lawful good",
            speed:{
                fly: true,
                swim: true,
                walk: true,
                climb: false,
            },
            legendary: true,
            Environment: {
                Desert: false,
                Mountain: false,
                Grassland: false,
                Forest: false,
                Hill: false,
                Swamp: true,
                Urban: false,
                Artic: false,
                Underdark: false,
                Underwater: false,
                Coastal: true
            }
        },
        {   id:9,
            name: "Adult Copper Dragon",
            cr:14,
            type: "dragon",
            size: "huge",
            ac: 18,
            hp: 184,
            initiative: 0,
            alignment: "chaotic good",
            speed:{
                fly: true,
                swim: false,
                walk: true,
                climb: false,
            },
            legendary: true,
            Environment: {
                Desert: false,
                Mountain: true,
                Grassland: false,
                Forest: false,
                Hill: true,
                Swamp: false,
                Urban: false,
                Artic: false,
                Underdark: false,
                Underwater: false,
                Coastal: false
            }
        },
        {   id:10,
            name: "Adult Gold Dragon",
            cr:17,
            type: "dragon",
            size: "huge",
            ac: 19,
            hp: 256,
            initiative: 0,
            alignment: "lawful good",
            speed:{
                fly: true,
                swim: true,
                walk: true,
                climb: false,
            },
            legendary: true,
            Environment: {
                Desert: false,
                Mountain: true,
                Grassland: false,
                Forest: false,
                Hill: false,
                Swamp: false,
                Urban: false,
                Artic: false,
                Underdark: false,
                Underwater: false,
                Coastal: true
            }
        },
        
    ]

export default creatures;