import Head from 'next/head'
import { useState } from 'react'
import Header from '../components/Header'
import MonstersBlock from '../components/MonstersBlock'
import PlayersBlock from '../components/PlayersBlock'
import {
  ContainerST,
  ContentST,
  MainST,
  SideBarST,
  SubtitleST
} from '../components/sharedstyles'

export default function Home() {

  // players data
  const [players, setPlayers] = useState([]);
  // monsters on the enconter data
  const [encounterMonsters, setEncounterMonsters] = useState([]);

  // general functions
  function lvlToXP ( lvl ){
    let xpNumber;

    if(lvl == 1){ xpNumber = 25 }
    else if (lvl == 2){ xpNumber = 50 }
    else if (lvl == 3){ xpNumber = 75 }
    else if (lvl == 4){ xpNumber = 125 }
    else if (lvl == 5){ xpNumber = 250 }
    else if (lvl == 6){ xpNumber = 300 }
    else if (lvl == 7){ xpNumber = 350 }
    else if (lvl == 8){ xpNumber = 450 }
    else if (lvl == 9){ xpNumber = 550 }
    else if (lvl == 10){ xpNumber = 600 }
    else if (lvl == 11){ xpNumber = 800 }
    else if (lvl == 12){ xpNumber = 1000 }
    else if (lvl == 13){ xpNumber = 1100 }
    else if (lvl == 14){ xpNumber = 1250 }
    else if (lvl == 15){ xpNumber = 1400 }
    else if (lvl == 16){ xpNumber = 1600 }
    else if (lvl == 17){ xpNumber = 2000 }
    else if (lvl == 18){ xpNumber = 2100 }
    else if (lvl == 19){ xpNumber = 2400 }
    else if (lvl == 20){ xpNumber = 2800 }
    else{}

    return xpNumber;
  }

  function sumElem (list){
    let totalSum = 0;
    for(let e=0; e < list.length; e++){
      totalSum += list[e];
    }

    return totalSum;
  }

/*   function addNumberPlayers (){
    

  });

    playerListLvl = [1];
    for(let p=0; p<numberPlayers+1; p++){
      playerListLvl[p] = 1;
      playerListXP[p] = lvlToXP(playerListLvl[p]);
    }

    setPartyXP(sumElem(playerListXP));

    console.log('addNumberPlayer:')
    console.log(playerListLvl)
    console.log(playerListXP)
  }

  function removeNumberPlayers (){
    if(numberPlayers>1){
      setNumberPlayers( numberPlayers -1 )
    }

    playerListLvl = [1];
    for(let p=0; p<numberPlayers-1; p++){
      playerListLvl[p] = 1;
      playerListXP[p] = lvlToXP(playerListLvl[p]);
    }

    setPartyXP(sumElem(playerListXP));

    console.log('removeNumberPlayer:')
    console.log(playerListLvl)
    console.log(playerListXP)
  } */

  return (
    <div>
      <Head>
        <title>Dungeon Beholder Encounter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <MainST>
        <ContainerST>
          <SideBarST>
            <PlayersBlock />
            <MonstersBlock />
          </SideBarST>
          <ContentST>
            <SubtitleST>Dungeon Beholder Encounter</SubtitleST>
            <p>Lista de monstros</p>
          </ContentST>
        </ContainerST>
      </MainST>
    </div>
  )
}
