import Head from 'next/head'
import Header from '../components/Header'
import PlayersBlock from '../components/PlayersBlock'
import {
  ContainerST,
  ContentST,
  MainST,
  SideBarST,
  SubtitleST
} from '../components/sharedstyles'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dungeon Beholder Encounter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <MainST>
        <ContainerST>
          <SideBarST>
            <SubtitleST>Players Group</SubtitleST>
            <PlayersBlock />
          </SideBarST>
          <ContentST>
            <SubtitleST>Dungeon Beholder Encounter</SubtitleST>
            <p>Lista de monstros</p>
          </ContentST>
        </ContainerST>
      </MainST>
    </div>
  )
}
